// <copyright file="PacketBindings.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

enum class ItemStorageKind : uint32_t
{
Inventory = 0, ///< The inventory storage.
Trade = 1, ///< The trade storage.
Vault = 2, ///< The vault storage.
ChaosMachine = 3, ///< The chaos machine storage.
PlayerShop = 4, ///< The player shop storage.
PetTrainer = 5, ///< The pet trainer dialog storage.
Refinery = 6, ///< The storage of the refinery of the elphis npc.
Smelting = 7, ///< The storage of the smelting dialog of the osbourne npc.
ItemRestore = 8, ///< The storage of the item restore dialog of the jerridon npc.
ChaosCardMaster = 9, ///< The storage of the chaos card master dialog.
CherryBlossomSpirit = 10, ///< The storage of the cherry blossom spirit dialog.
SeedCrafting = 11, ///< The storage of the seed crafting dialog.
SeedSphereCrafting = 12, ///< The storage of the seed sphere crafting dialog.
SeedMountCrafting = 13, ///< The storage of the seed sphere mount dialog.
SeedUnmountCrafting = 14, ///< The storage of the seed sphere unmount dialog.
};

enum class LegacyQuestState : uint32_t
{
Undefined = 0, ///< The state is undefined. This value is used when there is no quest defined for a specific index
Active = 1, ///< The quest is active and in progress.
Complete = 2, ///< The quest was completed.
Inactive = 3, ///< The quest is inactive, that means it isn't active and wasn't completed yet.
};

enum class CharacterClassNumber : uint32_t
{
DarkWizard = 0, ///< Value for the dark wizard character class.
SoulMaster = 2, ///< Value for the soul master character class.
GrandMaster = 3, ///< Value for the grand master character class.
DarkKnight = 4, ///< Value for the dark knight character class.
BladeKnight = 6, ///< Value for the blade knight character class.
BladeMaster = 7, ///< Value for the blade master character class.
FairyElf = 8, ///< Value for the fairy elf character class.
MuseElf = 10, ///< Value for the muse elf character class.
HighElf = 11, ///< Value for the high elf character class.
MagicGladiator = 12, ///< Value for the magic gladiator character class.
DuelMaster = 13, ///< Value for the duel master character class.
DarkLord = 16, ///< Value for the dark lord character class.
LordEmperor = 17, ///< Value for the lord emperor character class.
Summoner = 20, ///< Value for the summoner character class.
BloodySummoner = 22, ///< Value for the bloody summoner character class.
DimensionMaster = 23, ///< Value for the dimension master character class.
RageFighter = 24, ///< Value for the rage fighter character class.
FistMaster = 25, ///< Value for the fist master character class.
};

enum class CharacterStatAttribute : uint32_t
{
Strength = 0, ///< The strength attribute.
Agility = 1, ///< The agility attribute.
Vitality = 2, ///< The vitality attribute.
Energy = 3, ///< The energy attribute.
Leadership = 4, ///< The leadership attribute.
};

enum class CharacterHeroState : uint32_t
{
New = 0, ///< The character is new and has the highest state.
Hero = 1, ///< The character is a hero.
LightHero = 2, ///< The character is a hero, but the state is almost gone.
Normal = 3, ///< The character is in a neutral state.
PlayerKillWarning = 4, ///< The character killed another character, and has a kill warning.
PlayerKiller1stStage = 5, ///< The character killed two characters, and has some restrictions.
PlayerKiller2ndStage = 6, ///< The character killed more than two characters, and has hard restrictions.
};

enum class LogOutType : uint32_t
{
CloseGame = 0, ///< The player wants to close the game.
BackToCharacterSelection = 1, ///< The player wants to go back to the character selection screen.
BackToServerSelection = 2, ///< The player wants to go back to the server selection screen.
};

enum class MiniGameType : uint32_t
{
Undefined = 0, ///< Undefined mini game type.
DevilSquare = 1, ///< The devil square mini game.
BloodCastle = 2, ///< The blood castle mini game.
CursedTemple = 3, ///< The cursed temple mini game.
ChaosCastle = 4, ///< The chaos castle mini game.
IllusionTemple = 5, ///< The illusion temple mini game.
Doppelganger = 6, ///< The doppelgänger mini game.
};

enum class AuctionResult : uint32_t
{
Success = 0, ///< Success.
Disabled = 1, ///< Disabled.
NotAuthenticated = 2, ///< NotAuthenticated.
StateRestricted = 3, ///< StateRestricted.
LevelTooLow = 4, ///< LevelTooLow.
AccountTooNew = 5, ///< AccountTooNew.
AccountRestricted = 6, ///< AccountRestricted.
RateLimited = 7, ///< RateLimited.
InvalidRequest = 8, ///< InvalidRequest.
UnsupportedCurrency = 9, ///< UnsupportedCurrency.
CurrencyConfigurationInvalid = 10, ///< CurrencyConfigurationInvalid.
InvalidDuration = 11, ///< InvalidDuration.
InvalidPrice = 12, ///< InvalidPrice.
InvalidFruitBasket = 13, ///< InvalidFruitBasket.
ItemNotFound = 14, ///< ItemNotFound.
ItemNotEligible = 15, ///< ItemNotEligible.
ListingLimitReached = 16, ///< ListingLimitReached.
InsufficientCurrency = 17, ///< InsufficientCurrency.
ListingNotFound = 18, ///< ListingNotFound.
ListingNotActive = 19, ///< ListingNotActive.
ListingExpired = 20, ///< ListingExpired.
StaleListing = 21, ///< StaleListing.
SelfTrade = 22, ///< SelfTrade.
AlreadyHighestBidder = 23, ///< AlreadyHighestBidder.
BidTooLow = 24, ///< BidTooLow.
BuyoutUnavailable = 25, ///< BuyoutUnavailable.
CannotCancelWithBid = 26, ///< CannotCancelWithBid.
CollectionNotFound = 27, ///< CollectionNotFound.
InvalidClaimQuantity = 28, ///< InvalidClaimQuantity.
InventoryFull = 29, ///< InventoryFull.
MoneyLimit = 30, ///< MoneyLimit.
AlreadyProcessed = 31, ///< AlreadyProcessed.
ServiceUnavailable = 32, ///< ServiceUnavailable.
};

enum class AuctionCurrencyMode : uint32_t
{
Zen = 0, ///< Zen.
Chaos = 1, ///< Chaos.
Bless = 2, ///< Bless.
Soul = 3, ///< Soul.
Life = 4, ///< Life.
Creation = 5, ///< Creation.
Guardian = 6, ///< Guardian.
Harmony = 7, ///< Harmony.
Fruits = 8, ///< Fruits.
};

enum class AuctionCategory : uint32_t
{
Weapon = 0, ///< Weapon.
Armor = 1, ///< Armor.
Wing = 2, ///< Wing.
PetHelper = 3, ///< PetHelper.
JewelMaterial = 4, ///< JewelMaterial.
Consumable = 5, ///< Consumable.
Miscellaneous = 6, ///< Miscellaneous.
};

enum class AuctionSort : uint32_t
{
PriceAscending = 0, ///< PriceAscending.
PriceDescending = 1, ///< PriceDescending.
EndingSoonest = 2, ///< EndingSoonest.
Newest = 3, ///< Newest.
};

enum class AuctionListingStatus : uint32_t
{
Active = 0, ///< Active.
Sold = 1, ///< Sold.
Expired = 2, ///< Expired.
Cancelled = 3, ///< Cancelled.
AdminRemoved = 4, ///< AdminRemoved.
};

enum class AuctionCollectionKind : uint32_t
{
PurchasedItem = 0, ///< PurchasedItem.
ReturnedItem = 1, ///< ReturnedItem.
SaleProceeds = 2, ///< SaleProceeds.
OutbidRefund = 3, ///< OutbidRefund.
TenderChange = 4, ///< TenderChange.
AdminRefund = 5, ///< AdminRefund.
};

enum class AuctionCollectionStatus : uint32_t
{
Pending = 0, ///< Pending.
PartiallyClaimed = 1, ///< PartiallyClaimed.
Claimed = 2, ///< Claimed.
};

enum class AuctionOperationType : uint32_t
{
Create = 0, ///< Create.
Bid = 1, ///< Bid.
Buyout = 2, ///< Buyout.
Cancel = 3, ///< Cancel.
Collect = 4, ///< Collect.
};

enum class AuctionNotificationKind : uint32_t
{
Outbid = 0, ///< Outbid.
Sold = 1, ///< Sold.
Bought = 2, ///< Bought.
Expired = 3, ///< Expired.
Returned = 4, ///< Returned.
Collected = 5, ///< Collected.
AdminAdjusted = 6, ///< AdminAdjusted.
};

